import { type ComponentProps } from "react";

import { cn } from "@/lib/utils";

/**
 * Material Symbols names used across the app. Keeping this as a union means a
 * typo fails typechecking instead of silently rendering the ligature text.
 */
export type IconName =
  | "accessible"
  | "account_balance"
  | "account_tree"
  | "add"
  | "add_circle"
  | "add_task"
  | "alarm_on"
  | "api"
  | "arrow_back"
  | "arrow_back_ios_new"
  | "arrow_downward"
  | "arrow_forward"
  | "arrow_forward_ios"
  | "arrow_upward"
  | "article"
  | "assignment_ind"
  | "assignment_late"
  | "auto_awesome"
  | "auto_graph"
  | "autorenew"
  | "badge"
  | "block"
  | "bolt"
  | "bookmark"
  | "bug_report"
  | "build"
  | "calendar_today"
  | "call_split"
  | "cancel"
  | "check"
  | "check_box"
  | "check_circle"
  | "chevron_left"
  | "chevron_right"
  | "close"
  | "cloud"
  | "cloud_circle"
  | "cloud_sync"
  | "cloud_upload"
  | "code"
  | "content_copy"
  | "copy_all"
  | "crop_free"
  | "dashboard"
  | "delete"
  | "description"
  | "document_scanner"
  | "donut_small"
  | "download"
  | "draft"
  | "edit"
  | "error"
  | "expand_more"
  | "fact_check"
  | "file_download"
  | "file_upload"
  | "filter_alt_off"
  | "filter_list"
  | "find_in_page"
  | "fit_screen"
  | "flag"
  | "folder_open"
  | "folder_shared"
  | "folder_zip"
  | "forward_to_inbox"
  | "gavel"
  | "gpp_maybe"
  | "group"
  | "group_work"
  | "groups"
  | "headset_mic"
  | "help"
  | "help_center"
  | "help_outline"
  | "history_edu"
  | "hourglass_top"
  | "hub"
  | "image"
  | "info"
  | "input"
  | "integration_instructions"
  | "inventory_2"
  | "key"
  | "keyboard"
  | "layers"
  | "lightbulb"
  | "link"
  | "lock"
  | "logout"
  | "mail"
  | "memory"
  | "menu"
  | "menu_book"
  | "model_training"
  | "monitoring"
  | "more_vert"
  | "navigate_before"
  | "navigate_next"
  | "notifications"
  | "notifications_active"
  | "open_in_new"
  | "outgoing_mail"
  | "output"
  | "payments"
  | "pending_actions"
  | "person"
  | "person_search"
  | "picture_as_pdf"
  | "policy"
  | "priority_high"
  | "progress_activity"
  | "psychology"
  | "radio_button_checked"
  | "radio_button_unchecked"
  | "rate_review"
  | "receipt_long"
  | "refresh"
  | "remove"
  | "replay"
  | "report_problem"
  | "restart_alt"
  | "rocket_launch"
  | "rotate_right"
  | "rule"
  | "save"
  | "save_as"
  | "scanner"
  | "schedule"
  | "schema"
  | "science"
  | "search"
  | "security"
  | "send"
  | "settings"
  | "sort"
  | "speed"
  | "stacked_bar_chart"
  | "support_agent"
  | "swap_horiz"
  | "sync"
  | "sync_problem"
  | "table_chart"
  | "task_alt"
  | "terminal"
  | "timelapse"
  | "timer"
  | "toggle_on"
  | "token"
  | "trending_down"
  | "trending_up"
  | "troubleshoot"
  | "tune"
  | "undo"
  | "unfold_more"
  | "upload"
  | "upload_file"
  | "verified"
  | "verified_user"
  | "view_carousel"
  | "visibility"
  | "visibility_off"
  | "vpn_key"
  | "warning"
  | "webhook"
  | "zoom_in"
  | "zoom_out";

type IconProps = Omit<ComponentProps<"span">, "children"> & {
  name: IconName;
  /** Optical size in px; Material Symbols is drawn on a 24px grid. */
  size?: number;
};

export function Icon({ name, size = 20, className, style, ...props }: IconProps) {
  return (
    <span
      aria-hidden="true"
      translate="no"
      className={cn("material-symbols-outlined shrink-0 select-none leading-none", className)}
      style={{ fontSize: size, width: size, height: size, ...style }}
      {...props}
    >
      {name}
    </span>
  );
}
